/**
 * Curated manifest for the NVIDIA robotics graph.
 *
 * The fetch script (scripts/fetch-nvidia-projects.ts) reads this config, pulls
 * repo metadata + READMEs from the GitHub API, and emits
 * src/nvidia-graph/projects.data.json (committed, so the page works statically).
 *
 * Tune the org list, keyword filters, domain rules, and edges here.
 */

export interface DomainDef {
  id: string;
  label: string;
  color: string;
  // Lowercased substrings scored against name + description + topics.
  keywords: string[];
}

export interface OrgSource {
  org: string;
  // Pull every non-fork repo regardless of keyword match.
  includeAll?: boolean;
}

// Repos matched by keyword only must have at least this many stars to make the
// graph (allowlist and includeAll orgs bypass this). Keeps tiny experiments and
// tangentially-related research repos out of the map.
export const minAutoStars = 50;

export interface ManualNode {
  id: string;
  label: string;
  domain: string;
  description: string;
  homepage?: string;
}

export type EdgeType = "dependsOn" | "partOf" | "relatedTo";

export interface EdgeDef {
  source: string;
  target: string;
  type: EdgeType;
  // Relation strength, 0 to 1. Drives edge width/opacity and layout pull
  // (fcose ideal edge length) in the graph UI. Undefined -> neutral default
  // styling.
  score?: number;
}

export interface Config {
  domains: DomainDef[];
  orgs: OrgSource[];
  // owner/repo allowlist, guaranteed to be fetched even if keywords miss.
  include: string[];
  // owner/repo (or bare repo names) to skip.
  exclude: string[];
  // Lowercased substrings in name/description/topics that flag a repo as robotics-related.
  includeKeywords: string[];
  // Non-repo products that belong on the map regardless of a GitHub host.
  manual: ManualNode[];
  // Explicit domain assignments (by owner/repo) that beat keyword scoring.
  domainOverrides: Record<string, string>;
  // Org -> umbrella manual node: every repo in the org gets a partOf edge.
  orgProducts: Record<string, string>;
  edges: EdgeDef[];
  // Cap for stored README markdown, per repo.
  readmeMaxBytes: number;
  // Summary length in chars (surface copy in the side panel).
  summaryMaxChars: number;
}

export const config: Config = {
  domains: [
    {
      id: "simulation",
      label: "Simulation & Physics",
      color: "#8ab4f8",
      keywords: [
        "simulation", "sim", "physics", "physx", "omniverse", "warp", "newton",
        "render", "usd", "synthetic", "digital twin", "gpu-accelerated simulation",
      ],
    },
    {
      id: "learning",
      label: "Robot Learning",
      color: "#7ee787",
      keywords: [
        "robot learning", "learning", "reinforcement", "rl", "policy", "isaac lab",
        "isaaclab", "orbit", "isaac gym", "gym", "imitation", "manipulation",
        "curobo", "motion planning", "grasp", "skill", "diffusion",
      ],
    },
    {
      id: "foundation",
      label: "Foundation Models",
      color: "#d2a8ff",
      keywords: [
        "gr00t", "groot", "foundation model", "vla", "vision-language-action",
        "world model", "humanoid", "cosmos", "n1", "robot model", "mobility",
      ],
    },
    {
      id: "ros",
      label: "Isaac ROS & Middleware",
      color: "#ffb454",
      keywords: [
        "ros", "ros2", "isaac_ros", "perception", "slam", "detection",
        "segmentation", "depth", "navigation", "path planning", "vslam",
        "stereo", "pose estimation", "benchmark", "middleware",
      ],
    },
    {
      id: "hardware",
      label: "Jetson & Edge",
      color: "#f0883e",
      keywords: [
        "jetson", "embedded", "edge", "jetpack", "camera", "sensor", "mipi",
        "thor", "inference", "halos", "deepstream", "tensorrt", "triton",
        "video analytics", "inference server", "edge ai", "edge inference",
      ],
    },
    {
      id: "teleop",
      label: "Teleoperation & Motion",
      color: "#5ea8f5",
      keywords: [
        "teleop", "teleoperation", "xr", "retarget", "motion capture",
        "human motion", "ik", "whole-body",
      ],
    },
    {
      id: "data",
      label: "Data & Generative AI",
      color: "#79c0ff",
      keywords: [
        "dataset", "data pipeline", "synthetic data", "tokenizer", "curation",
        "blueprint", "agent skills", "generative", "reconstruction",
      ],
    },
  ],
  orgs: [
    { org: "NVIDIA" },
    { org: "NVIDIA-ISAAC-ROS", includeAll: true },
    { org: "NVIDIA-Omniverse" },
    { org: "NVIDIA-AI-IOT" },
    { org: "isaac-sim", includeAll: true },
    { org: "NVlabs" },
    { org: "NVIDIA-Cosmos", includeAll: true },
    { org: "triton-inference-server" },
    // cuVSLAM, nvblox, cuMotion — core SLAM/mapping/motion-planning libs,
    // plus real LIDAR sensor drivers (velodyne_lidar, sick_lidar_tim571).
    { org: "nvidia-isaac", includeAll: true },
    // holoscan-sdk / holohub — real-time edge sensor & video processing SDK.
    { org: "nvidia-holoscan", includeAll: true },
  ],
  include: [
    "NVIDIA/Isaac-GR00T",
    "NVIDIA/IsaacTeleop",
    "NVIDIA/GR00T-Dreams",
    "NVIDIA/cosmos",
    "NVIDIA/warp",
    "NVIDIA/DreamDojo",
    "NVIDIA/soma-retargeter",
    "NVIDIA/halos-outside-in-safety",
    "isaac-sim/IsaacLab",
    "isaac-sim/IsaacGymEnvs",
    "NVlabs/HOVER",
    "NVlabs/GR00T-WholeBodyControl",
    "NVlabs/EAGLE",
    "NVlabs/COMPASS",
    "NVIDIA-AI-IOT/jetson-containers",
    "NVIDIA-AI-IOT/redtail",
    "NVIDIA-AI-IOT/jetcamera",
    "NVIDIA-ISAAC-ROS/isaac_ros_manipulation",
    "NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation",
    "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam",
    "NVIDIA-ISAAC-ROS/isaac_ros_detect_and_track",
    "NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation",
    "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth",
    "NVIDIA-ISAAC-ROS/isaac_ros_common",
    "NVIDIA-ISAAC-ROS/isaac_ros_rosbridge_suite",
    "NVIDIA-ISAAC-ROS/isaac_ros_nvblox",
    "NVIDIA-ISAAC-ROS/isaac_ros_deploy",
    "NVIDIA-ISAAC-ROS/isaac_ros_object_detection",
    "NVIDIA-AI-IOT/cuPCL",
    "NVIDIA/cuOpt-resources",
    "rapidsai/cuspatial",
    "rapidsai/cusignal",
    "NVIDIA/cutlass",
    "NVIDIA/cccl",
    "NVIDIA/DALI",
    "NVIDIA/nvmath-python",
    "rapidsai/cugraph",
    "rapidsai/cudf",
    "rapidsai/rmm",
    "NVIDIA/cuda-samples",
    "NVIDIA/CUDALibrarySamples",
    "NVIDIA/nvImageCodec",
  ],
  exclude: [
    ".github",
    "NVIDIA-ISAAC-ROS/.github",
    "NVIDIA-ISAAC-ROS/NVIDIA-ISAAC-ROS.github.io",
    "isaac-sim/.github",
    "samples",
    "training-containers",
    "uuid",
  ],
  includeKeywords: [
    "robot", "robotic", "isaac", "gr00t", "manipulat", "teleop", "vla",
    "vision-language-action", "humanoid", "world model", "physical ai",
    "motion planning", "grasp", "curobo", "slam", "retarget", "path planning",
    "navigation", "autonomous machines", "diffusion policy", "robot learning",
    // video / edge inference
    "deepstream", "video analytic", "video stream", "tensorrt", "triton",
    "inference server", "edge ai", "edge inference", "jetson", "pose estimation",
    "object detection", "computer vision", "video codec", "camera",
  ],
  manual: [
    {
      id: "isaac-sim",
      label: "NVIDIA Isaac Sim",
      domain: "simulation",
      description:
        "NVIDIA's robotics simulation platform built on Omniverse — physically based virtual worlds for developing, testing and validating autonomous machines.",
      homepage: "https://developer.nvidia.com/isaac/sim",
    },
    {
      id: "nvidia-omniverse",
      label: "NVIDIA Omniverse",
      domain: "simulation",
      description:
        "Open platform for building physically based 3D simulations and digital twins; the substrate under Isaac Sim.",
      homepage: "https://developer.nvidia.com/omniverse",
    },
    {
      id: "newton",
      label: "Newton Physics",
      domain: "simulation",
      description:
        "Open-source, GPU-accelerated, extensible physics engine co-developed by Google DeepMind and Disney Research, built on NVIDIA Warp and OpenUSD; managed by the Linux Foundation.",
      homepage: "https://developer.nvidia.com/newton-physics",
    },
    {
      id: "nvidia-jetson",
      label: "NVIDIA Jetson",
      domain: "hardware",
      description:
        "Embedded AI computer family (Orin, Thor) used to deploy Isaac and AI pipelines on autonomous machines at the edge.",
      homepage: "https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/",
    },
    {
      id: "jetpack",
      label: "JetPack SDK",
      domain: "hardware",
      description: "The SDK that bundles Linux for Tegra, CUDA and AI/tooling onto Jetson modules.",
      homepage: "https://developer.nvidia.com/embedded/jetpack",
    },
    {
      id: "isaac-ros",
      label: "NVIDIA Isaac ROS",
      domain: "ros",
      description:
        "Collection of NVIDIA-accelerated, low-latency ROS 2 packages for autonomous robots on Jetson and other NVIDIA platforms.",
      homepage: "https://developer.nvidia.com/isaac/ros",
    },
    {
      id: "nvidia-halos",
      label: "NVIDIA Halos",
      domain: "hardware",
      description:
        "NVIDIA's physical AI safety platform — perception and outside-in safety systems to safeguard warehouse and road robots.",
      homepage: "https://www.nvidia.com/en-us/deploy/halos/",
    },
    {
      id: "nvidia-isaac",
      label: "NVIDIA Isaac",
      domain: "data",
      description:
        "The umbrella robotics development platform spanning Isaac Sim, Isaac Lab, Isaac ROS, GR00T foundation models and Cosmos.",
      homepage: "https://developer.nvidia.com/isaac",
    },
  ],
  orgProducts: {
    "NVIDIA-ISAAC-ROS": "isaac-ros",
    "NVIDIA-Omniverse": "nvidia-omniverse",
    "NVIDIA-AI-IOT": "nvidia-jetson",
  },
  domainOverrides: {
    // Triton is edge/cloud inference serving infra, not robotics research —
    // keyword scoring would otherwise scatter its repos across domains.
    "triton-inference-server/server": "hardware",
    "triton-inference-server/client": "hardware",
    "triton-inference-server/core": "hardware",
    "triton-inference-server/backend": "hardware",
    "triton-inference-server/python_backend": "hardware",
    "triton-inference-server/pytorch_backend": "hardware",
    "triton-inference-server/onnxruntime_backend": "hardware",
    "triton-inference-server/tensorrtllm_backend": "hardware",
    "triton-inference-server/dali_backend": "hardware",
    "triton-inference-server/model_analyzer": "hardware",
    "triton-inference-server/model_navigator": "hardware",
    "triton-inference-server/pytriton": "hardware",
    "triton-inference-server/tutorials": "hardware",
    // SLAM/mapping core libs -> group with their Isaac ROS wrappers.
    "nvidia-isaac/cuVSLAM": "ros",
    "nvidia-isaac/nvblox": "ros",
    "nvidia-isaac/nvblox_mindmap": "ros",
    "nvidia-isaac/pyCuSFM": "ros",
    "nvidia-isaac/cuNLS": "ros",
    // Motion generation -> group with curobo / isaac_ros_cumotion.
    "nvidia-isaac/cumotion": "learning",
    // LIDAR/sensor hardware drivers.
    "nvidia-isaac/velodyne_lidar": "hardware",
    "nvidia-isaac/sick_lidar_tim571": "hardware",
    "nvidia-isaac/laikago_lidar_mount": "hardware",
    "nvidia-isaac/sick_safetyscanners_isaac": "hardware",
    "nvidia-isaac/econ_camera_steereocam": "hardware",
    "nvidia-isaac/lips_AE400": "hardware",
    "nvidia-isaac/kaya-robot": "hardware",
    // Holoscan: real-time edge sensor/video processing SDK.
    "nvidia-holoscan/holoscan-sdk": "hardware",
    "nvidia-holoscan/holohub": "hardware",
    "nvidia-holoscan/holoscan-sensor-bridge": "hardware",
    "nvidia-holoscan/holoscan-cli": "hardware",
    "nvidia-holoscan/holoscan-docs": "hardware",
    "nvidia-holoscan/holoscan-perf-tools": "hardware",
    "nvidia-holoscan/holoscan-test-suite": "hardware",
    "nvidia-holoscan/holoscan-federated-analytics": "hardware",
    "nvidia-holoscan/meta-tegra-holoscan": "hardware",
  },
  edges: [
    { source: "NVIDIA/cccl", target: "NVIDIA/cuda-samples", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/CUDALibrarySamples", target: "NVIDIA/cuda-samples", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA/cuda-samples", target: "NVIDIA/cutlass", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/pix2pixHD", target: "nvidia-cosmos/cosmos-transfer1", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/DreamDojo", target: "NVIDIA/pix2pixHD", type: "relatedTo", score: 0.35 },
    { source: "NVIDIA/pix2pixHD", target: "NVlabs/Eagle", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/Eagle", target: "nvidia-cosmos/cosmos-reason2", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/cosmos", target: "NVlabs/Eagle", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/AHA", target: "NVlabs/Eagle", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/Eagle", target: "NVlabs/vla0", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/CUDALibrarySamples", target: "NVIDIA/cccl", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/cccl", target: "NVIDIA/cutlass", type: "relatedTo", score: 0.55 },
    { source: "rapidsai/cugraph", target: "rapidsai/cusignal", type: "relatedTo", score: 0.5 },
    { source: "rapidsai/cugraph", target: "rapidsai/cuspatial", type: "relatedTo", score: 0.55 },
    { source: "rapidsai/cugraph", target: "rapidsai/rmm", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/alpagym", target: "NVlabs/alpasim", type: "relatedTo", score: 0.95 },
    { source: "NVlabs/alpamayo", target: "NVlabs/alpasim", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/alpamayo-recipes", target: "NVlabs/alpasim", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/alpamayo2", target: "NVlabs/alpasim", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/alpasim", target: "NVlabs/physical_ai_av", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/HOVER", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/HOVER", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/COMPASS", target: "NVlabs/HOVER", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/GR00T-WholeBodyControl", target: "NVlabs/HOVER", type: "relatedTo", score: 0.8 },
    { source: "NVlabs/HOVER", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.7 },
    { source: "rapidsai/cusignal", target: "rapidsai/rmm", type: "relatedTo", score: 0.55 },
    { source: "rapidsai/cuspatial", target: "rapidsai/rmm", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/Lidar_AI_Solution", target: "NVIDIA-AI-IOT/cuPCL", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/cuPCL", target: "NVIDIA-AI-IOT/ros2_tao_pointpillars", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/cuPCL", target: "nvidia-isaac/nvblox", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/cuPCL", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/CUDALibrarySamples", target: "NVIDIA/nvmath-python", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/cutlass", target: "NVIDIA/nvmath-python", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_libraries", target: "NVIDIA/video-sdk-samples", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_compression", target: "NVIDIA/video-sdk-samples", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/DALI", target: "NVIDIA/video-sdk-samples", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/DeepStream", target: "NVIDIA/video-sdk-samples", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/nvImageCodec", target: "NVIDIA/video-sdk-samples", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/soma-retargeter", target: "NVlabs/GLAMR", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/GLAMR", target: "NVlabs/blade", type: "relatedTo", score: 0.8 },
    { source: "NVlabs/GEM-X", target: "NVlabs/GLAMR", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/GLAMR", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/ncore", target: "NVlabs/physical_ai_av", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/alpamayo-coc-autolabeler", target: "NVlabs/physical_ai_av", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/alpamayo-recipes", target: "NVlabs/physical_ai_av", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/alpamayo2", target: "NVlabs/physical_ai_av", type: "relatedTo", score: 0.65 },
    { source: "isaac-sim/IsaacAutomator", target: "isaac-sim/isaac-launchable", type: "relatedTo", score: 0.65 },
    { source: "isaac-sim/IsaacAutomator", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.85 },
    { source: "isaac-sim/IsaacAutomator", target: "isaac-sim/IsaacLab-Arena", type: "relatedTo", score: 0.7 },
    { source: "isaac-sim/IsaacAutomator", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-Omniverse/IsaacSim-dockerfiles", target: "isaac-sim/IsaacAutomator", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/OSMO", target: "isaac-sim/IsaacAutomator", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/storm", target: "nvidia-isaac/cumotion", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/curobo", target: "NVlabs/storm", type: "relatedTo", score: 0.95 },
    { source: "NVlabs/cuTAMP", target: "NVlabs/storm", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson-stereo-depth", target: "NVIDIA/3DObjectReconstruction", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/3DObjectReconstruction", target: "nvidia-isaac/nvblox", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/3DObjectReconstruction", target: "nvidia-isaac/video_to_data", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/3DObjectReconstruction", target: "NVIDIA/ncore", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/3DObjectReconstruction", target: "NVlabs/3DGM", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/3DObjectReconstruction", target: "NVlabs/latentfusion", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/ncore", target: "nvidia-isaac/video_to_data", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/ncore", target: "nvidia-omniverse", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-Omniverse/ovrtx", target: "NVIDIA/ncore", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/6dof-graspnet", target: "NVlabs/acronym", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/acronym", target: "NVlabs/contact_graspnet", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/DefGraspSim", target: "NVlabs/acronym", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/GraspGen", target: "NVlabs/acronym", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/GraspGenX", target: "NVlabs/acronym", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/acronym", target: "NVlabs/scene_synthesizer", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/jetson-device-skills", target: "jetpack", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/jetson-device-skills", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson-device-skills", target: "nvidia-jetson", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/jetson-device-skills", target: "NVIDIA/skills", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/alpamayo", target: "NVlabs/alpamayo-coc-autolabeler", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/alpamayo-coc-autolabeler", target: "NVlabs/alpamayo-recipes", type: "relatedTo", score: 0.9 },
    { source: "NVlabs/alpamayo-coc-autolabeler", target: "NVlabs/alpamayo1.5", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/alpamayo-coc-autolabeler", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.8 },
    { source: "isaac-sim/IsaacSim", target: "nvidia-isaac/video_to_data", type: "relatedTo", score: 0.5 },
    { source: "nvidia-cosmos/cosmos-xenna", target: "nvidia-isaac/video_to_data", type: "relatedTo", score: 0.45 },
    { source: "nvidia-isaac", target: "nvidia-isaac/video_to_data", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/IsaacTeleop", target: "nvidia-isaac/video_to_data", type: "relatedTo", score: 0.45 },
    { source: "nvidia-cosmos/cosmos-cookbook", target: "nvidia-cosmos/cosmos-xenna", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-xenna", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/DALI", target: "nvidia-cosmos/cosmos-xenna", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/Lidar_AI_Solution", target: "NVIDIA/ACCV-Lab", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_tao_pointpillars", target: "NVIDIA/ACCV-Lab", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/ACCV-Lab", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/ACCV-Lab", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.45 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/urdf-importer-extension", type: "relatedTo", score: 0.6 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/urdf-importer-extension", type: "relatedTo", score: 0.95 },
    { source: "isaac-sim/mjcf-importer-extension", target: "isaac-sim/urdf-importer-extension", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/soma-retargeter", target: "NVlabs/blade", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/GEM-X", target: "NVlabs/blade", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/gxf", target: "isaac-ros", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-ISAAC-ROS/gxf", target: "nvidia-holoscan/holoscan-sdk", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/gxf", target: "NVIDIA-ISAAC-ROS/isaac_ros_common", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/gxf", target: "NVIDIA-ISAAC-ROS/isaac_ros_nitros", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/mjcf-importer-extension", type: "relatedTo", score: 0.55 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/mjcf-importer-extension", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA-ISAAC-ROS/r2s_gw", target: "isaac-ros", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/greenwave_monitor", target: "NVIDIA-ISAAC-ROS/r2s_gw", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_common", target: "NVIDIA-ISAAC-ROS/r2s_gw", type: "relatedTo", score: 0.4 },
    { source: "nvidia-isaac", target: "nvidia-isaac/ota-file-service", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac/isaac_mission_control", target: "nvidia-isaac/ota-file-service", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac/isaac_mission_dispatch", target: "nvidia-isaac/ota-file-service", type: "relatedTo", score: 0.6 },
    { source: "isaac-ros", target: "nvidia-isaac", type: "relatedTo", score: 0.95 },
    { source: "isaac-sim", target: "nvidia-isaac", type: "relatedTo", score: 0.95 },
    { source: "nvidia-halos", target: "nvidia-isaac", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac", target: "nvidia-isaac/econ_camera_steereocam", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac", target: "nvidia-isaac/kaya-robot", type: "relatedTo", score: 0.55 },
    { source: "nvidia-isaac", target: "nvidia-isaac/laikago_lidar_mount", type: "relatedTo", score: 0.55 },
    { source: "nvidia-isaac", target: "nvidia-isaac/lips_AE400", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac", target: "nvidia-isaac/sick_lidar_tim571", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac", target: "nvidia-isaac/sick_safetyscanners_isaac", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac", target: "nvidia-isaac/velodyne_lidar", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac", target: "nvidia-omniverse", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/cosmos", target: "nvidia-isaac", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA/halos-outside-in-safety", target: "nvidia-isaac", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/Isaac-GR00T", target: "nvidia-isaac", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/OSMO", target: "nvidia-isaac", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/skills", target: "nvidia-isaac", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-cookbook", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-dependencies", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-predict1", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-predict2", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-predict2.5", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-reason1", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-reason2", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-rl", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-transfer1", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/cosmos", target: "nvidia-cosmos/cosmos-transfer2.5", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/DreamDojo", target: "NVIDIA/cosmos", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/cosmos", target: "NVIDIA/flashdreams", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/GR00T-Dreams", target: "NVIDIA/cosmos", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/Isaac-GR00T", target: "NVIDIA/cosmos", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/cosmos", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/Isaac-GR00T", target: "isaac-sim/IsaacLabEvalTasks", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/Isaac-GR00T", target: "isaac-sim/Sim-to-Real-SO-101-Workshop", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/Isaac-GR00T", target: "nvidia-cosmos/cosmos-reason2", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/Isaac-GR00T", target: "nvidia-isaac/gr00t-leapp-export", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA/Isaac-GR00T", target: "nvidia-isaac/leapp", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/GR00T-Dreams", target: "NVIDIA/Isaac-GR00T", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/Isaac-GR00T", target: "NVlabs/AHA", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/Isaac-GR00T", target: "NVlabs/GR00T-VisualSim2Real", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/Isaac-GR00T", target: "NVlabs/GR00T-WholeBodyControl", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/Isaac-GR00T", target: "NVlabs/vla-perf", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/Isaac-GR00T", target: "NVlabs/vla0", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", target: "NVlabs/GR00T-WholeBodyControl", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/GR00T-WholeBodyControl", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.8 },
    { source: "NVlabs/COMPASS", target: "NVlabs/GR00T-WholeBodyControl", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/GR00T-WholeBodyControl", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/alpamayo", target: "NVlabs/alpamayo-recipes", type: "relatedTo", score: 0.9 },
    { source: "NVlabs/alpamayo", target: "NVlabs/alpamayo1.5", type: "relatedTo", score: 0.95 },
    { source: "NVlabs/alpamayo", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.85 },
    { source: "nvidia-cosmos/cosmos-predict1", target: "nvidia-cosmos/cosmos-predict2.5", type: "relatedTo", score: 0.85 },
    { source: "nvidia-cosmos/cosmos-predict2", target: "nvidia-cosmos/cosmos-predict2.5", type: "relatedTo", score: 0.95 },
    { source: "nvidia-cosmos/cosmos-predict2.5", target: "nvidia-cosmos/cosmos-reason1", type: "relatedTo", score: 0.55 },
    { source: "nvidia-cosmos/cosmos-predict2.5", target: "nvidia-cosmos/cosmos-transfer2.5", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/DreamDojo", target: "nvidia-cosmos/cosmos-predict2", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/DreamDojo", target: "NVIDIA/flashdreams", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/DreamDojo", target: "NVIDIA/GR00T-Dreams", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/DreamDojo", target: "NVlabs/PointWorld", type: "relatedTo", score: 0.5 },
    { source: "nvidia-cosmos/cosmos-reason1", target: "nvidia-cosmos/cosmos-reason2", type: "relatedTo", score: 0.95 },
    { source: "nvidia-cosmos/cosmos-predict2", target: "nvidia-cosmos/cosmos-transfer1", type: "relatedTo", score: 0.6 },
    { source: "nvidia-cosmos/cosmos-transfer1", target: "nvidia-cosmos/cosmos-transfer2.5", type: "relatedTo", score: 0.95 },
    { source: "NVlabs/GR00T-VisualSim2Real", target: "nvidia-cosmos/cosmos-transfer1", type: "relatedTo", score: 0.4 },
    { source: "nvidia-cosmos/cosmos-predict1", target: "nvidia-cosmos/cosmos-predict2", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA/GR00T-Dreams", target: "nvidia-cosmos/cosmos-predict2", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/GR00T-Dreams", target: "NVIDIA/flashdreams", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/AHA", target: "NVlabs/vla0", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/RVT", target: "NVlabs/vla0", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/vla-perf", target: "NVlabs/vla0", type: "relatedTo", score: 0.7 },
    { source: "nvidia-cosmos/cosmos-cookbook", target: "nvidia-cosmos/cosmos-dependencies", type: "relatedTo", score: 0.7 },
    { source: "nvidia-cosmos/cosmos-cookbook", target: "nvidia-cosmos/cosmos-rl", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/AHA", target: "nvidia-cosmos/cosmos-reason2", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/alpamayo2", target: "nvidia-cosmos/cosmos-reason2", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/alpagym", target: "NVlabs/alpamayo1.5", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/alpamayo-recipes", target: "NVlabs/alpamayo1.5", type: "relatedTo", score: 0.9 },
    { source: "NVlabs/alpamayo1.5", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.85 },
    { source: "NVlabs/alpagym", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/alpamayo-recipes", target: "NVlabs/alpamayo2", type: "relatedTo", score: 0.95 },
    { source: "NVlabs/alpagym", target: "NVlabs/alpamayo-recipes", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/ros2_benchmark", target: "NVlabs/vla-perf", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/Electron", target: "NVIDIA-AI-IOT/jetson-trashformers", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "NVIDIA-AI-IOT/jetson-trashformers", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson-trashformers", target: "NVIDIA-AI-IOT/turtlebot3", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/jetson-trashformers", target: "nvidia-jetson", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_deploy", target: "nvidia-isaac/gr00t-leapp-export", type: "relatedTo", score: 0.75 },
    { source: "nvidia-isaac/gr00t-leapp-export", target: "nvidia-isaac/leapp", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation", target: "NVlabs/FoundationPose", type: "relatedTo", score: 0.9 },
    { source: "NVlabs/CenterPose", target: "NVlabs/FoundationPose", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/Deep_Object_Pose", target: "NVlabs/FoundationPose", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/FoundationPose", target: "NVlabs/diff-dope", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/DREAM", target: "NVlabs/FoundationPose", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/FoundationPose", target: "NVlabs/GraspGen", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/FoundationPose", target: "NVlabs/GraspGenX", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/FoundationPose", target: "NVlabs/latentfusion", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/FoundationPose", target: "NVlabs/object_centric_diffusion", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_mapping_and_localization", target: "nvidia-isaac/cuVSLAM", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam", target: "nvidia-isaac/cuVSLAM", type: "relatedTo", score: 0.95 },
    { source: "nvidia-isaac/cuNLS", target: "nvidia-isaac/cuVSLAM", type: "relatedTo", score: 0.55 },
    { source: "nvidia-isaac/cuVSLAM", target: "nvidia-isaac/pyCuSFM", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/geomapnet", target: "nvidia-isaac/cuVSLAM", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/learningrigidity", target: "nvidia-isaac/cuVSLAM", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_map_localization", target: "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_mapping_and_localization", target: "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_visual_slam", target: "NVIDIA-ISAAC-ROS/nova_carter", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", target: "nvidia-isaac/nvblox", type: "relatedTo", score: 0.95 },
    { source: "nvidia-isaac/nvblox", target: "nvidia-isaac/nvblox_mindmap", type: "relatedTo", score: 0.85 },
    { source: "NVlabs/3DGM", target: "nvidia-isaac/nvblox", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/FLAT", target: "nvidia-isaac/nvblox", type: "relatedTo", score: 0.35 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation", target: "NVlabs/Deep_Object_Pose", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/CenterPose", target: "NVlabs/Deep_Object_Pose", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/Deep_Object_Pose", target: "NVlabs/diff-dope", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/DREAM", target: "NVlabs/Deep_Object_Pose", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/Deep_Object_Pose", target: "NVlabs/latentfusion", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream_pose_estimation", target: "NVIDIA-AI-IOT/trt_pose", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/ros2_trt_pose", target: "NVIDIA-AI-IOT/trt_pose", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/torch2trt", target: "NVIDIA-AI-IOT/trt_pose", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/trt_pose", target: "NVIDIA-AI-IOT/trt_pose_hand", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/trt_pose", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/trt_pose", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/Foresee-Navigation", target: "NVIDIA-AI-IOT/redtail", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/Formula1Epoch", target: "NVIDIA-AI-IOT/redtail", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "NVIDIA-AI-IOT/redtail", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/jetracer", target: "NVIDIA-AI-IOT/redtail", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/redtail", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/DALI", target: "NVIDIA/retinanet-examples", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/object-detection-tensorrt-example", target: "NVIDIA/retinanet-examples", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/retinanet-examples", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/retinanet-examples", target: "NVlabs/AL-MDN", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/retinanet-examples", target: "NVlabs/wetectron", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/Nav2-with-Isaac-ROS-GEMs", target: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", target: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", target: "NVIDIA-ISAAC-ROS/nova_carter", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nvblox", target: "nvidia-isaac/nvblox_mindmap", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation", target: "NVlabs/CenterPose", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/soma-retargeter", target: "NVlabs/GEM-X", type: "relatedTo", score: 0.85 },
    { source: "NVlabs/GEM-X", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson_benchmarks", target: "jetpack", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetnet", target: "NVIDIA-AI-IOT/jetson_benchmarks", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson_benchmarks", target: "NVIDIA-AI-IOT/jetson_dla_tutorial", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/jetson_benchmarks", target: "NVIDIA-AI-IOT/tf_to_trt_image_classification", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/jetson_benchmarks", target: "nvidia-jetson", type: "relatedTo", score: 0.8 },
    { source: "NVlabs/AL-MDN", target: "NVlabs/wetectron", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/DIODE", target: "NVlabs/wetectron", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_common", target: "isaac-ros", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_common", target: "NVIDIA-ISAAC-ROS/isaac_ros_data_tools", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_common", target: "NVIDIA-ISAAC-ROS/isaac_ros_examples", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_common", target: "NVIDIA-ISAAC-ROS/isaac_ros_nitros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac-ros-cli", target: "NVIDIA-ISAAC-ROS/isaac_ros_common", type: "relatedTo", score: 0.65 },
    { source: "nvidia-isaac/cuNLS", target: "nvidia-isaac/pyCuSFM", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/latentfusion", target: "nvidia-isaac/pyCuSFM", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/ros2_torch_trt", target: "NVIDIA/object-detection-tensorrt-example", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/object-detection-tensorrt-example", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/ros2_trt_pose", target: "NVIDIA-AI-IOT/trt_pose_hand", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/trt_pose_hand", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/trt_pose_hand", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/greenwave_monitor", target: "isaac-ros", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/greenwave_monitor", target: "NVIDIA-ISAAC-ROS/ros2_benchmark", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/greenwave_monitor", target: "NVIDIA-ISAAC-ROS/ros2_framework_perf", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/3DGM", target: "NVlabs/latentfusion", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/diff-dope", target: "NVlabs/latentfusion", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nitros", target: "isaac-ros", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nitros", target: "NVIDIA-ISAAC-ROS/isaac_ros_nitros_bridge", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nitros", target: "NVIDIA-ISAAC-ROS/isaac_ros_noetic_interfaces", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/ros2_nanollm", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/jetson-copilot", target: "NVIDIA-AI-IOT/ros2_nanollm", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_jetson", target: "NVIDIA-AI-IOT/ros2_nanollm", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_nanollm", target: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/ros2_nanollm", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_apriltag", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/isaac_ros_apriltag", target: "NVIDIA-ISAAC-ROS/isaac_ros_apriltag", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_apriltag", target: "NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline", target: "isaac-ros", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_argus_camera", target: "NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_compression", target: "NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth", target: "NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline", target: "NVIDIA-ISAAC-ROS/isaac_ros_sipl_camera", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/AL-MDN", target: "NVlabs/DIODE", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/jetson-stereo-depth", target: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_depth_segmentation", target: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_depth", target: "NVlabs/FLAT", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/ros2_benchmark", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_benchmark", target: "NVIDIA-ISAAC-ROS/ros2_benchmark", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-ISAAC-ROS/ros2_benchmark", target: "NVIDIA-ISAAC-ROS/ros2_framework_perf", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", target: "NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_image_segmentation", target: "NVIDIA-ISAAC-ROS/isaac_ros_object_detection", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/ros2_jetson", target: "NVIDIA-AI-IOT/ros2_torch_trt", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/ros2_torch_trt", target: "NVIDIA-AI-IOT/torch2trt", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/ros2_torch_trt", target: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_torch_trt", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/Lidar_AI_Solution", target: "NVIDIA-AI-IOT/ros2_tao_pointpillars", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/ros2_jetson", target: "NVIDIA-AI-IOT/ros2_tao_pointpillars", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_tao_pointpillars", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_manipulation", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_manipulation", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cumotion", target: "NVIDIA-ISAAC-ROS/isaac_ros_manipulation", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_argus_camera", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/argus_camera", target: "NVIDIA-ISAAC-ROS/isaac_ros_argus_camera", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_argus_camera", target: "NVIDIA-ISAAC-ROS/isaac_ros_nova", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_argus_camera", target: "NVIDIA-ISAAC-ROS/isaac_ros_sipl_camera", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_argus_camera", target: "NVIDIA-ISAAC-ROS/sensor_mounting_rig", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cloud_control", target: "nvidia-isaac/isaac_mission_dispatch", type: "relatedTo", score: 0.85 },
    { source: "nvidia-isaac/isaac_mission_control", target: "nvidia-isaac/isaac_mission_dispatch", type: "relatedTo", score: 0.9 },
    { source: "nvidia-isaac/SWAGGER", target: "nvidia-isaac/isaac_mission_dispatch", type: "relatedTo", score: 0.6 },
    { source: "nvidia-isaac/SWAGGER", target: "nvidia-isaac/isaac_mission_control", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/jetcam", target: "NVIDIA-AI-IOT/jetson-stereo-depth", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/jetson-stereo-depth", target: "nvidia-jetson", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetson-stereo-depth", target: "NVlabs/FLAT", type: "relatedTo", score: 0.3 },
    { source: "NVIDIA-AI-IOT/Foresee-Navigation", target: "NVIDIA-AI-IOT/Nav2-with-Isaac-ROS-GEMs", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/Foresee-Navigation", target: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/Foresee-Navigation", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/3DGM", target: "NVlabs/PointWorld", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/ros2_deepstream", target: "NVIDIA-AI-IOT/ros2_jetson", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_jetson", target: "NVIDIA-AI-IOT/ros2_jetson_stats", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/ros2_jetson", target: "NVIDIA-AI-IOT/ros2_trt_pose", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/ros2_jetson", target: "nvidia-jetson", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_map_localization", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_map_localization", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_map_localization", target: "NVIDIA-ISAAC-ROS/isaac_ros_mapping_and_localization", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_map_localization", target: "NVlabs/geomapnet", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cloud_control", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cloud_control", target: "NVIDIA-ISAAC-ROS/nova_carter", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cloud_control", target: "nvidia-isaac/isaac_mission_control", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cloud_control", target: "NVIDIA/halos-outside-in-safety", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_depth_segmentation", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/isaac_ros_object_detection", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_perceptor", target: "NVIDIA-ISAAC-ROS/nova_carter", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/ros2_trt_pose", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_compression", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_libraries", target: "NVIDIA-ISAAC-ROS/isaac_ros_compression", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/ros2_jetson_stats", target: "NVIDIA-ISAAC-ROS/isaac_ros_jetson", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/ros2_jetson_stats", target: "nvidia-jetson", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetson-intro-to-distillation", target: "NVlabs/DIODE", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/isaac_ros_apriltag", target: "isaac-ros", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/isaac_ros_apriltag", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_depth_segmentation", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_depth_segmentation", target: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", type: "relatedTo", score: 0.75 },
    { source: "isaac-sim/IsaacLab", target: "nvidia-isaac/nvblox_mindmap", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/PointWorld", target: "nvidia-isaac/nvblox_mindmap", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/Nav2-with-Isaac-ROS-GEMs", target: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/Nav2-with-Isaac-ROS-GEMs", target: "NVIDIA-ISAAC-ROS/nova_carter", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/Nav2-with-Isaac-ROS-GEMs", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_freespace_segmentation", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_benchmark", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_benchmark", target: "NVIDIA-ISAAC-ROS/ros2_framework_perf", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_jetson", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_jetson", target: "nvidia-jetson", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/ros2_framework_perf", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_mapping_and_localization", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "nvidia-isaac/cuNLS", target: "nvidia-isaac/cumotion", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_examples", target: "isaac-ros", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_data_tools", target: "NVIDIA-ISAAC-ROS/isaac_ros_examples", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nova", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nova", target: "NVIDIA-ISAAC-ROS/isaac_ros_sipl_camera", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nova", target: "NVIDIA-ISAAC-ROS/nova_carter", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nova", target: "NVIDIA-ISAAC-ROS/nova_developer_kit", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nitros_bridge", target: "isaac-ros", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_nitros_bridge", target: "NVIDIA-ISAAC-ROS/isaac_ros_noetic_interfaces", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-ISAAC-ROS/isaac-ros-cli", target: "isaac-ros", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_deploy", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_deploy", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_deploy", target: "NVIDIA-ISAAC-ROS/isaac_ros_learned_policies", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_deploy", target: "nvidia-isaac/leapp", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_noetic_interfaces", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_data_tools", target: "isaac-ros", type: "relatedTo", score: 0.75 },
    { source: "isaac-ros", target: "isaac-sim/IsaacSim-ros_workspaces", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cumotion", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_learned_policies", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_object_detection", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_robots", target: "isaac-ros", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_sipl_camera", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_teleop", target: "isaac-ros", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/nova_carter", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/nova_developer_kit", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-ISAAC-ROS/sensor_mounting_rig", target: "isaac-ros", type: "relatedTo", score: 0.4 },
    { source: "isaac-ros", target: "nvidia-jetson", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_learned_policies", target: "NVIDIA-ISAAC-ROS/isaac_ros_robots", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", target: "NVIDIA-ISAAC-ROS/isaac_ros_robots", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_robots", target: "NVIDIA-ISAAC-ROS/isaac_ros_teleop", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_learned_policies", target: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/ChatRTX", target: "NVIDIA/TensorRT-LLM", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/GenerativeAIExamples", target: "NVIDIA/TensorRT-LLM", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/Model-Optimizer", target: "NVIDIA/TensorRT-LLM", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/TensorRT-LLM", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/TensorRT-Edge-LLM", target: "NVIDIA/TensorRT-LLM", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/TensorRT-LLM", target: "NVIDIA/TensorRT-RTX", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/TensorRT-LLM", target: "triton-inference-server/tensorrtllm_backend", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/nanoowl", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/nanosam", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/sdg_pallet_model", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/tensorrt_plugin_generator", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/tf_to_trt_image_classification", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/tf_trt_models", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/torch2trt", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/whisper_trt", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/yolo_deepstream", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/Model-Optimizer", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/sampleQAT", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/Stable-Diffusion-WebUI-TensorRT", target: "NVIDIA/TensorRT", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/TensorRT-Edge-LLM", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/TensorRT-Incubator", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/tensorrt-laboratory", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/TensorRT-RTX", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/TensorRT", target: "NVIDIA/trt-samples-for-hackathon-cn", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA/TensorRT", target: "triton-inference-server/model_navigator", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/TensorRT", target: "triton-inference-server/tensorrt_backend", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/deepstream_triton_model_deploy", target: "triton-inference-server/server", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/tao-toolkit-triton-apps", target: "triton-inference-server/server", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "triton-inference-server/server", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/tensorrt-laboratory", target: "triton-inference-server/server", type: "relatedTo", score: 0.45 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/server", type: "relatedTo", score: 0.85 },
    { source: "triton-inference-server/client", target: "triton-inference-server/server", type: "relatedTo", score: 0.9 },
    { source: "triton-inference-server/common", target: "triton-inference-server/server", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/core", target: "triton-inference-server/server", type: "relatedTo", score: 0.9 },
    { source: "triton-inference-server/dali_backend", target: "triton-inference-server/server", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/fil_backend", target: "triton-inference-server/server", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/model_analyzer", target: "triton-inference-server/server", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/model_navigator", target: "triton-inference-server/server", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/onnxruntime_backend", target: "triton-inference-server/server", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/python_backend", target: "triton-inference-server/server", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/pytorch_backend", target: "triton-inference-server/server", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/pytriton", target: "triton-inference-server/server", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/server", target: "triton-inference-server/tensorflow_backend", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/server", target: "triton-inference-server/tensorrt_backend", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/server", target: "triton-inference-server/tensorrtllm_backend", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/server", target: "triton-inference-server/triton_cli", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/server", target: "triton-inference-server/tutorials", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA/DALI", target: "NVIDIA/nvImageCodec", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/DALI", target: "triton-inference-server/dali_backend", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/jetnet", target: "NVIDIA-AI-IOT/torch2trt", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/nanosam", target: "NVIDIA-AI-IOT/torch2trt", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/tf_trt_models", target: "NVIDIA-AI-IOT/torch2trt", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/torch2trt", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/ChatRTX", target: "NVIDIA/GenerativeAIExamples", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/GenerativeAIExamples", target: "NVIDIA/Model-Optimizer", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/GenerativeAIExamples", target: "NVIDIA/Stable-Diffusion-WebUI-TensorRT", type: "relatedTo", score: 0.35 },
    { source: "NVIDIA-AI-IOT/clip-distillation", target: "NVIDIA/Model-Optimizer", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/jetson-intro-to-distillation", target: "NVIDIA/Model-Optimizer", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/yolo_deepstream", target: "NVIDIA/Model-Optimizer", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/Model-Optimizer", target: "NVIDIA/sampleQAT", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "NVIDIA-AI-IOT/jetcam", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "NVIDIA-AI-IOT/jetcard", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "NVIDIA-AI-IOT/jetracer", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "NVIDIA-AI-IOT/my-jetson-nano-baseboard", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/jetbot", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetson-copilot", target: "NVIDIA/ChatRTX", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_4.x_apps", target: "NVIDIA-AI-IOT/deepstream_python_apps", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_dockers", target: "NVIDIA-AI-IOT/deepstream_python_apps", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream_pose_estimation", target: "NVIDIA-AI-IOT/deepstream_python_apps", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA-AI-IOT/deepstream_reference_apps", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA-AI-IOT/deepstream_tao_apps", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream-occupancy-analytics", target: "NVIDIA-AI-IOT/deepstream_python_apps", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream-retail-analytics", target: "NVIDIA-AI-IOT/deepstream_python_apps", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA-AI-IOT/face-mask-detection", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA-AI-IOT/jetson-multicamera-pipelines", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA-AI-IOT/redaction_with_deepstream", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA-AI-IOT/ros2_deepstream", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_python_apps", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/Lidar_AI_Solution", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/tensorrt_plugin_generator", target: "NVIDIA/trt-samples-for-hackathon-cn", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/TensorRT-Incubator", target: "NVIDIA/trt-samples-for-hackathon-cn", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/deepstream_parallel_inference_app", target: "NVIDIA-AI-IOT/deepstream_reference_apps", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream_reference_apps", target: "NVIDIA-AI-IOT/deepstream_tao_apps", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/Deepstream-Dewarper-App", target: "NVIDIA-AI-IOT/deepstream_reference_apps", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_reference_apps", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_reference_apps", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/Formula1Epoch", target: "NVIDIA-AI-IOT/jetracer", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetcam", target: "NVIDIA-AI-IOT/jetracer", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetcard", target: "NVIDIA-AI-IOT/jetracer", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/jetracer", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/jetson-gpio", target: "jetpack", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/my-jetson-nano-baseboard", target: "NVIDIA/jetson-gpio", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/jetson-gpio", target: "nvidia-jetson", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/tensorrtllm_backend", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/tensorrt_backend", target: "triton-inference-server/tensorrtllm_backend", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/clip-distillation", target: "NVIDIA-AI-IOT/nanosam", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson-intro-to-distillation", target: "NVIDIA-AI-IOT/nanosam", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/nanoowl", target: "NVIDIA-AI-IOT/nanosam", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/nanosam", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "triton-inference-server/client", target: "triton-inference-server/tutorials", type: "relatedTo", score: 0.65 },
    { source: "triton-inference-server/model_analyzer", target: "triton-inference-server/tutorials", type: "relatedTo", score: 0.5 },
    { source: "triton-inference-server/triton_cli", target: "triton-inference-server/tutorials", type: "relatedTo", score: 0.45 },
    { source: "triton-inference-server/client", target: "triton-inference-server/pytriton", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/python_backend", target: "triton-inference-server/pytriton", type: "relatedTo", score: 0.6 },
    { source: "triton-inference-server/client", target: "triton-inference-server/common", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/tf_to_trt_image_classification", target: "NVIDIA-AI-IOT/tf_trt_models", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/tf_trt_models", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/python_backend", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/deepstream_tao_apps", target: "NVIDIA-AI-IOT/yolo_deepstream", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/yolo_deepstream", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/yolo_deepstream", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/yolo_deepstream", target: "NVIDIA/sampleQAT", type: "relatedTo", score: 0.55 },
    { source: "triton-inference-server/model_analyzer", target: "triton-inference-server/model_navigator", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/model_analyzer", target: "triton-inference-server/triton_cli", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/whisper_trt", target: "NVIDIA/TensorRT-Edge-LLM", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/TensorRT-Edge-LLM", target: "nvidia-jetson", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/argus_camera", target: "NVIDIA-AI-IOT/jetcam", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetcam", target: "NVIDIA-AI-IOT/jetcard", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetcam", target: "NVIDIA-AI-IOT/jetson-multicamera-pipelines", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetcam", target: "nvidia-jetson", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/tf_to_trt_image_classification", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_lpr_app", target: "NVIDIA-AI-IOT/deepstream_tao_apps", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/deepstream_tao_apps", target: "NVIDIA-AI-IOT/tao-toolkit-triton-apps", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/deepstream_tao_apps", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_tao_apps", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/nanoowl", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/nanoowl", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/common", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/core", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/dali_backend", type: "relatedTo", score: 0.7 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/fil_backend", type: "relatedTo", score: 0.75 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/onnxruntime_backend", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/pytorch_backend", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/tensorflow_backend", type: "relatedTo", score: 0.8 },
    { source: "triton-inference-server/backend", target: "triton-inference-server/tensorrt_backend", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/deepstream-occupancy-analytics", target: "NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream-retail-analytics", target: "NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/deepstream_pose_estimation", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_pose_estimation", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA/TensorRT-Incubator", target: "NVIDIA/tensorrt-laboratory", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/clip-distillation", target: "NVIDIA-AI-IOT/jetson-intro-to-distillation", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/jetson-intro-to-distillation", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/jetson-intro-to-distillation", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_4.x_apps", target: "NVIDIA-AI-IOT/face-mask-detection", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/face-mask-detection", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/face-mask-detection", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/tensorrt_plugin_generator", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/tensorrt_plugin_generator", target: "NVIDIA/TensorRT-Incubator", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/deepstream-occupancy-analytics", target: "NVIDIA-AI-IOT/deepstream-retail-analytics", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/deepstream-occupancy-analytics", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream-occupancy-analytics", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/deepstream_lpr_app", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_lpr_app", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/jetson-rdma-picoevb", target: "jetpack", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/jetson-rdma-picoevb", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-cli", type: "relatedTo", score: 0.8 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-docs", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-federated-analytics", type: "relatedTo", score: 0.5 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-perf-tools", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-sdk", type: "relatedTo", score: 0.9 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-sensor-bridge", type: "relatedTo", score: 0.6 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/holoscan-test-suite", type: "relatedTo", score: 0.5 },
    { source: "nvidia-holoscan/holohub", target: "nvidia-holoscan/meta-tegra-holoscan", type: "relatedTo", score: 0.6 },
    { source: "nvidia-holoscan/holoscan-cli", target: "nvidia-holoscan/holoscan-sdk", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holoscan-docs", target: "nvidia-holoscan/holoscan-sdk", type: "relatedTo", score: 0.85 },
    { source: "nvidia-holoscan/holoscan-federated-analytics", target: "nvidia-holoscan/holoscan-sdk", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holoscan-perf-tools", target: "nvidia-holoscan/holoscan-sdk", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holoscan-sdk", target: "nvidia-holoscan/holoscan-sensor-bridge", type: "relatedTo", score: 0.8 },
    { source: "nvidia-holoscan/holoscan-sdk", target: "nvidia-holoscan/holoscan-test-suite", type: "relatedTo", score: 0.7 },
    { source: "nvidia-holoscan/holoscan-sdk", target: "nvidia-holoscan/meta-tegra-holoscan", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/jetcard", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/Audio2Face-3D-SDK", target: "NVIDIA/Maya-ACE", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/deepstream-retail-analytics", target: "NVIDIA-AI-IOT/redaction_with_deepstream", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/redaction_with_deepstream", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/redaction_with_deepstream", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/deepstream_4.x_apps", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/DeepStream_Coding_Agent", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/deepstream_dockers", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/deepstream_libraries", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-AI-IOT/deepstream_parallel_inference_app", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/deepstream_triton_model_deploy", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/Deepstream-Dewarper-App", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/deepstream-retail-analytics", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-AI-IOT/jetson-multicamera-pipelines", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/ros2_deepstream", target: "NVIDIA/DeepStream", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference", target: "NVIDIA-ISAAC-ROS/isaac_ros_object_detection", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/deepstream_dockers", target: "NVIDIA-AI-IOT/jetson-cloudnative-demo", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetson-cloudnative-demo", target: "NVIDIA-AI-IOT/jetson-platform-services", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/jetson-cloudnative-demo", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/jetson-copilot", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/jetson-platform-services", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "NVIDIA-AI-IOT/whisper_trt", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-AI-IOT/jetson-ai-lab", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/jetson-multicamera-pipelines", target: "nvidia-jetson", type: "relatedTo", score: 0.65 },
    { source: "triton-inference-server/onnxruntime_backend", target: "triton-inference-server/tensorrt_backend", type: "relatedTo", score: 0.55 },
    { source: "triton-inference-server/pytorch_backend", target: "triton-inference-server/tensorflow_backend", type: "relatedTo", score: 0.55 },
    { source: "triton-inference-server/common", target: "triton-inference-server/core", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/clip-distillation", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/jetson-copilot", target: "nvidia-jetson", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream_parallel_inference_app", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/whisper_trt", target: "nvidia-jetson", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/turtlebot3", target: "nvidia-isaac/kaya-robot", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-ISAAC-ROS/nova_carter", target: "nvidia-isaac/kaya-robot", type: "relatedTo", score: 0.4 },
    { source: "nvidia-isaac/kaya-robot", target: "nvidia-jetson", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/Stable-Diffusion-WebUI-TensorRT", target: "NVIDIA/TensorRT-RTX", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/ros2_deepstream", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/argus_camera", target: "NVIDIA-ISAAC-ROS/isaac_ros_sipl_camera", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/argus_camera", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_dockers", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_triton_model_deploy", target: "NVIDIA-AI-IOT/tao-toolkit-triton-apps", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/tao-toolkit-triton-apps", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/Electron", target: "NVIDIA-AI-IOT/turtlebot3", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/turtlebot3", target: "nvidia-jetson", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/my-jetson-nano-baseboard", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/deepstream_libraries", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_libraries", target: "NVIDIA/nvImageCodec", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/deepstream_triton_model_deploy", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/deepstream_4.x_apps", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/sdg_pallet_model", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/sdg_pallet_model", target: "NVIDIA-AI-IOT/synthetic_data_generation_training_workflow", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/sdg_pallet_model", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/DeepStream_Coding_Agent", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA-AI-IOT/DeepStream_Coding_Agent", target: "NVIDIA/skills", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/Electron", target: "NVIDIA-AI-IOT/Formula1Epoch", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/Formula1Epoch", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "NVIDIA/tegra-nouveau-rootfs", target: "jetpack", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/tegra-nouveau-rootfs", target: "nvidia-jetson", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/halos-outside-in-safety", target: "nvidia-halos", type: "relatedTo", score: 0.95 },
    { source: "NVIDIA-ISAAC-ROS/nova_carter", target: "NVIDIA-ISAAC-ROS/nova_developer_kit", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA-AI-IOT/jetson-platform-services", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/deepstream-retail-analytics", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "nvidia-holoscan/holoscan-sensor-bridge", target: "nvidia-holoscan/meta-tegra-holoscan", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/Deepstream-Dewarper-App", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "nvidia-isaac/laikago_lidar_mount", target: "nvidia-isaac/velodyne_lidar", type: "relatedTo", score: 0.55 },
    { source: "nvidia-isaac/sick_lidar_tim571", target: "nvidia-isaac/velodyne_lidar", type: "relatedTo", score: 0.4 },
    { source: "nvidia-holoscan/holoscan-cli", target: "nvidia-holoscan/holoscan-docs", type: "relatedTo", score: 0.5 },
    { source: "nvidia-holoscan/holoscan-perf-tools", target: "nvidia-holoscan/holoscan-test-suite", type: "relatedTo", score: 0.6 },
    { source: "nvidia-halos", target: "nvidia-isaac/sick_safetyscanners_isaac", type: "relatedTo", score: 0.4 },
    { source: "nvidia-isaac/sick_lidar_tim571", target: "nvidia-isaac/sick_safetyscanners_isaac", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-ISAAC-ROS/nova_developer_kit", target: "NVIDIA-ISAAC-ROS/sensor_mounting_rig", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_sipl_camera", target: "NVIDIA-ISAAC-ROS/sensor_mounting_rig", type: "relatedTo", score: 0.5 },
    { source: "jetpack", target: "nvidia-jetson", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-AI-IOT/Electron", target: "nvidia-jetson", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-AI-IOT/jetnet", target: "nvidia-jetson", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/jetson_dla_tutorial", target: "nvidia-jetson", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA-AI-IOT/synthetic_data_generation_training_workflow", target: "nvidia-jetson", type: "relatedTo", score: 0.4 },
    { source: "nvidia-isaac/econ_camera_steereocam", target: "nvidia-isaac/lips_AE400", type: "relatedTo", score: 0.6 },
    { source: "isaac-sim", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.85 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/isaac-launchable", type: "relatedTo", score: 0.8 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/isaac-xr-teleop-sample-client-apple", type: "relatedTo", score: 0.55 },
    { source: "isaac-sim/IsaacGymEnvs", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.75 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/IsaacLab-Arena", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/IsaacLabEvalTasks", type: "relatedTo", score: 0.8 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/IsaacLabExtensionTemplate", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/IsaacLabTutorial", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/IsaacSimZMQ", type: "relatedTo", score: 0.5 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/OmniIsaacGymEnvs", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/IsaacLab", target: "isaac-sim/Sim-to-Real-SO-101-Workshop", type: "relatedTo", score: 0.8 },
    { source: "isaac-sim/IsaacLab", target: "nvidia-cosmos/cosmos-rl", type: "relatedTo", score: 0.45 },
    { source: "isaac-sim/IsaacLab", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/OSMO", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/COMPASS", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/curobo", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/GR00T-VisualSim2Real", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/IsaacLabEureka", target: "isaac-sim/IsaacLab", type: "relatedTo", score: 0.85 },
    { source: "isaac-sim/IsaacGymEnvs", target: "isaac-sim/OmniIsaacGymEnvs", type: "relatedTo", score: 0.85 },
    { source: "NVlabs/DiffRL", target: "isaac-sim/IsaacGymEnvs", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/oscar", target: "isaac-sim/IsaacGymEnvs", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cumotion", target: "NVlabs/curobo", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/curobo", target: "nvidia-isaac/cumotion", type: "relatedTo", score: 0.75 },
    { source: "NVIDIA/warp", target: "NVlabs/curobo", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/collab-sim", target: "NVlabs/curobo", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/cuTAMP", target: "NVlabs/curobo", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/curobo", target: "NVlabs/oscar", type: "relatedTo", score: 0.5 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/OmniIsaacGymEnvs", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/oscar", target: "isaac-sim/OmniIsaacGymEnvs", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/6dof-graspnet", target: "NVlabs/GraspGen", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/GraspGen", target: "NVlabs/contact_graspnet", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/DefGraspSim", target: "NVlabs/GraspGen", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/GraspGen", target: "NVlabs/GraspGenX", type: "relatedTo", score: 0.95 },
    { source: "NVlabs/GraspGen", target: "NVlabs/object_centric_diffusion", type: "relatedTo", score: 0.45 },
    { source: "isaac-sim/IsaacLab-Arena", target: "isaac-sim/IsaacLabEvalTasks", type: "relatedTo", score: 0.6 },
    { source: "isaac-sim/IsaacLab-Arena", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/6dof-graspnet", target: "NVlabs/contact_graspnet", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/DefGraspSim", target: "NVlabs/contact_graspnet", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/GraspGenX", target: "NVlabs/contact_graspnet", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/PointWorld", target: "NVlabs/RVT", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/GRAIL", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/soma-retargeter", target: "NVlabs/GRAIL", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/GR00T-VisualSim2Real", target: "NVlabs/GRAIL", type: "relatedTo", score: 0.6 },
    { source: "NVlabs/GRAIL", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/alpagym", target: "nvidia-cosmos/cosmos-rl", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/DRAIL", target: "nvidia-cosmos/cosmos-rl", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/ACID", target: "NVlabs/RVT", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/AHA", target: "NVlabs/RVT", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/RVT", target: "NVlabs/handover-sim2real", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/RVT", target: "NVlabs/object_centric_diffusion", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/warp", target: "NVlabs/DiffRL", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/DRAIL", target: "NVlabs/DiffRL", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/DiffRL", target: "NVlabs/neural-robot-dynamics", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/geomapnet", target: "NVlabs/learningrigidity", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.75 },
    { source: "NVlabs/GR00T-VisualSim2Real", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.65 },
    { source: "NVlabs/ProtoMotions", target: "nvidia-isaac/WBC-AGILE", type: "relatedTo", score: 0.6 },
    { source: "isaac-sim/IsaacLabExtensionTemplate", target: "isaac-sim/IsaacLabTutorial", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/6dof-graspnet", target: "NVlabs/DefGraspSim", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cumotion", target: "nvidia-isaac/cumotion", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_cumotion", target: "NVlabs/cuTAMP", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA-AI-IOT/synthetic_data_generation_training_workflow", target: "NVlabs/scene_synthesizer", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/handover-sim", target: "NVlabs/scene_synthesizer", type: "relatedTo", score: 0.5 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/isaac-launchable", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA/warp", target: "NVlabs/DefGraspSim", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/DRAIL", target: "NVlabs/IsaacLabEureka", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/ACID", target: "NVlabs/oscar", type: "relatedTo", score: 0.4 },
    { source: "NVlabs/handover-sim2real", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.5 },
    { source: "NVlabs/handover-sim", target: "NVlabs/handover-sim2real", type: "relatedTo", score: 0.9 },
    { source: "NVlabs/cuTAMP", target: "nvidia-isaac/cumotion", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/COMPASS", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.5 },
    { source: "isaac-sim/IsaacLabEvalTasks", target: "isaac-sim/Sim-to-Real-SO-101-Workshop", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/ACID", target: "NVlabs/object_centric_diffusion", type: "relatedTo", score: 0.5 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/Sim-to-Real-SO-101-Workshop", type: "relatedTo", score: 0.55 },
    { source: "NVlabs/collab-sim", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.7 },
    { source: "NVIDIA/IsaacTeleop", target: "NVlabs/collab-sim", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA/warp", target: "newton", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA/soma-retargeter", target: "NVIDIA/warp", type: "relatedTo", score: 0.65 },
    { source: "NVIDIA/warp", target: "NVlabs/neural-robot-dynamics", type: "relatedTo", score: 0.55 },
    { source: "isaac-sim", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.95 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/isaac-teleop-device-plugins", type: "relatedTo", score: 0.5 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/isaacsim-app-template", type: "relatedTo", score: 0.85 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/IsaacSim-ros_workspaces", type: "relatedTo", score: 0.85 },
    { source: "isaac-sim/IsaacSim", target: "isaac-sim/IsaacSimZMQ", type: "relatedTo", score: 0.8 },
    { source: "isaac-sim/IsaacSim", target: "newton", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/synthetic_data_generation_training_workflow", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.65 },
    { source: "isaac-sim/IsaacSim", target: "nvidia-omniverse", type: "relatedTo", score: 0.85 },
    { source: "NVIDIA-Omniverse/IsaacSim-dockerfiles", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA-Omniverse/ovrtx", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.7 },
    { source: "NVlabs/handover-sim", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.45 },
    { source: "NVlabs/neural-robot-dynamics", target: "isaac-sim/IsaacSim", type: "relatedTo", score: 0.45 },
    { source: "NVIDIA/soma-retargeter", target: "NVlabs/ProtoMotions", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA/soma-retargeter", target: "newton", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-AI-IOT/synthetic_data_generation_training_workflow", target: "NVIDIA-Omniverse/ovrtx", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA-Omniverse/ovrtx", target: "nvidia-omniverse", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-Omniverse/IsaacSim-dockerfiles", target: "nvidia-omniverse", type: "relatedTo", score: 0.55 },
    { source: "NVIDIA-AI-IOT/synthetic_data_generation_training_workflow", target: "nvidia-omniverse", type: "relatedTo", score: 0.45 },
    { source: "isaac-sim", target: "isaac-sim/isaacsim-app-template", type: "relatedTo", score: 0.75 },
    { source: "isaac-sim/isaacsim-app-template", target: "nvidia-omniverse", type: "relatedTo", score: 0.6 },
    { source: "isaac-sim", target: "nvidia-omniverse", type: "relatedTo", score: 0.85 },
    { source: "newton", target: "nvidia-omniverse", type: "relatedTo", score: 0.5 },
    { source: "NVIDIA/IsaacTeleop", target: "isaac-sim/isaac-teleop-device-plugins", type: "relatedTo", score: 0.9 },
    { source: "NVIDIA/IsaacTeleop", target: "isaac-sim/isaac-xr-teleop-sample-client-apple", type: "relatedTo", score: 0.8 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", target: "NVIDIA/IsaacTeleop", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_teleop", target: "NVIDIA/IsaacTeleop", type: "relatedTo", score: 0.9 },
    { source: "isaac-sim/isaac-teleop-device-plugins", target: "isaac-sim/isaac-xr-teleop-sample-client-apple", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_teleop", target: "isaac-sim/isaac-teleop-device-plugins", type: "relatedTo", score: 0.6 },
    { source: "NVIDIA-ISAAC-ROS/isaac_ros_physical_ai", target: "NVIDIA-ISAAC-ROS/isaac_ros_teleop", type: "relatedTo", score: 0.7 },
  ],
  readmeMaxBytes: 64 * 1024,
  summaryMaxChars: 500,
};